import socket
s =socket.socket()
s.connect(('192.168.1.35',7777))
print('conectado')
s.sendall(b'*IDN?\n')
print('conectado')
data=s.recvfrom(35)
print(data[0].decode())
s.sendall(b'KRDG?A\n')
print('conectado')
data=s.recvfrom(10)
print(data[0].decode())
s.sendall(b'MOUT?\n')
print('conectado')
data=s.recvfrom(10)
print(data[0].decode())
s.sendall(b'MOUT1,1.0\n')
print('conectado')
data=s.recvfrom(10)
s.close()